credentials:
  usernames:
    test_user1:
      email: user1@gmail.com
      name: John Smith
      password: $2b$12$rQrgrX58iDlW2f5MXunhhewVUHbWCJC4rvQ3kyT6FXPPlCxQhkXCC
    test_user2:
      email: user2@gmail.com
      name: Rebecca Briggs
      password: $2b$12$YX2wR3UmBRQDXr5eyPeq/.BGVVBf9sQ20CuZu3mQfHOkZ6bMWGHdK
    test_user3:
      email: user3@gmail.com
      name: Rebecca Black
      password: $2b$12$xiU4BYllrOX6taU1TspVC.iHDn0GaF/fB4eUURIv6pl5uxBMStjAi
cookie:
  expiry_days: 30
  key: auth_key
  name: auth_cookie
